2018-12-20 12:31:28 ERROR  : Error connecting to the server: FATAL:  password authentication failed for user "chatbotdb"
FATAL:  password authentication failed for user "chatbotdb"

2018-12-20 12:31:39 ERROR  : ERROR:  function pg_last_xlog_receive_location() does not exist
LINE 1: ...E NULL END as inrecovery, CASE WHEN usesuper THEN pg_last_xl...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2018-12-20 12:31:40 ERROR  : Column not found in pgSet: usecreatedb
2018-12-20 12:31:40 ERROR  : Column not found in pgSet: usesuper
2018-12-20 12:31:41 ERROR  : Column not found in pgSet: upsince
2018-12-20 12:31:41 ERROR  : Column not found in pgSet: confloadedsince
2018-12-20 12:31:41 ERROR  : Column not found in pgSet: inrecovery
2018-12-20 12:31:42 ERROR  : Column not found in pgSet: replayloc
2018-12-20 12:31:42 ERROR  : Column not found in pgSet: receiveloc
2018-12-20 12:31:42 ERROR  : Column not found in pgSet: replay_timestamp
2018-12-20 12:31:42 ERROR  : Column not found in pgSet: isreplaypaused
2018-12-20 12:46:56 ERROR  : ERROR:  syntax error at or near "FOREIGN"
LINE 1: FOREIGN KEY (rid) REFERENCES TrainStats (rid) ON DELETE CASC...
        ^
2018-12-20 12:47:18 ERROR  : ERROR:  syntax error at or near "ADD"
LINE 1: ADD CONSTRAINT FOREIGN KEY (rid) REFERENCES TrainStats (rid)...
        ^
2018-12-20 13:32:05 ERROR  : could not connect to server: Connection timed out (0x0000274C/10060)
	Is the server running on host "178.62.30.249" and accepting
	TCP/IP connections on port 5432?

2018-12-20 15:04:22 ERROR  : ERROR:  syntax error at or near "inInfo"
LINE 1: inInfo.current_Location, trainInfo.desired_destination,train...
        ^
2018-12-20 15:56:59 ERROR  : ERROR:  syntax error at or near "date"
LINE 1: date,trainInfo.current_Location, trainInfo.desired_destinati...
        ^
2018-12-29 16:02:03 ERROR  : ERROR:  function pg_last_xlog_receive_location() does not exist
LINE 1: ...E NULL END as inrecovery, CASE WHEN usesuper THEN pg_last_xl...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2018-12-29 16:02:03 ERROR  : Column not found in pgSet: usecreatedb
2018-12-29 16:02:03 ERROR  : Column not found in pgSet: usesuper
2018-12-29 16:02:03 ERROR  : Column not found in pgSet: upsince
2018-12-29 16:02:04 ERROR  : Column not found in pgSet: confloadedsince
2018-12-29 16:02:04 ERROR  : Column not found in pgSet: inrecovery
2018-12-29 16:02:04 ERROR  : Column not found in pgSet: replayloc
2018-12-29 16:02:04 ERROR  : Column not found in pgSet: receiveloc
2018-12-29 16:02:04 ERROR  : Column not found in pgSet: replay_timestamp
2018-12-29 16:02:05 ERROR  : Column not found in pgSet: isreplaypaused
2018-12-29 16:44:10 ERROR  : ERROR:  cannot drop table trainstats because other objects depend on it
DETAIL:  constraint traininfo_rid_fkey on table traininfo depends on table trainstats
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
2018-12-29 16:59:34 ERROR  : ERROR:  relation "trainstats" does not exist
LINE 2: ...ats.actual_arrival FROM trainInfo FULL OUTER JOIN trainStats...
                                                             ^
2018-12-29 17:00:33 ERROR  : ERROR:  missing FROM-clause entry for table "trainstats"
LINE 2: ...ual_arrival FROM trainInfo WHERE EXTRACT(dow FROM trainStats...
                                                             ^
2018-12-29 17:43:28 ERROR  : ERROR:  function pg_last_xlog_receive_location() does not exist
LINE 1: ...E NULL END as inrecovery, CASE WHEN usesuper THEN pg_last_xl...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2018-12-29 17:43:28 ERROR  : Column not found in pgSet: usecreatedb
2018-12-29 17:43:28 ERROR  : Column not found in pgSet: usesuper
2018-12-29 17:43:28 ERROR  : Column not found in pgSet: upsince
2018-12-29 17:43:28 ERROR  : Column not found in pgSet: confloadedsince
2018-12-29 17:43:28 ERROR  : Column not found in pgSet: inrecovery
2018-12-29 17:43:29 ERROR  : Column not found in pgSet: replayloc
2018-12-29 17:43:29 ERROR  : Column not found in pgSet: receiveloc
2018-12-29 17:43:29 ERROR  : Column not found in pgSet: replay_timestamp
2018-12-29 17:43:29 ERROR  : Column not found in pgSet: isreplaypaused
2019-01-05 12:56:43 ERROR  : ERROR:  function pg_last_xlog_receive_location() does not exist
LINE 1: ...E NULL END as inrecovery, CASE WHEN usesuper THEN pg_last_xl...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2019-01-05 12:56:44 ERROR  : Column not found in pgSet: usecreatedb
2019-01-05 12:56:45 ERROR  : Column not found in pgSet: usesuper
2019-01-05 12:56:45 ERROR  : Column not found in pgSet: upsince
2019-01-05 12:56:45 ERROR  : Column not found in pgSet: confloadedsince
2019-01-05 12:56:45 ERROR  : Column not found in pgSet: inrecovery
2019-01-05 12:56:45 ERROR  : Column not found in pgSet: replayloc
2019-01-05 12:56:46 ERROR  : Column not found in pgSet: receiveloc
2019-01-05 12:56:46 ERROR  : Column not found in pgSet: replay_timestamp
2019-01-05 12:56:46 ERROR  : Column not found in pgSet: isreplaypaused
